apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kill-job.fullname" . }}
  labels:
    {{- include "kill-job.labels" . | nindent 4 }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
              - "-RUST_MAIN_APP_URL=http://rust-main.default.svc.cluster.local"
              - "-GO_MAIN_APP_URL=http://go-main.default.svc.cluster.local" 
            command: 
            - /app/main
          restartPolicy: Never