apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kill-job.fullname" . }}
  labels:
    {{- include "kill-job.labels" . | nindent 4 }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }} 
            env:
              - name: RUST_MAIN_APP_URL
                value: http://rust-main.default.svc.cluster.local
              - name: GO_MAIN_APP_URL
                value: http://go-main.default.svc.cluster.local
              - name: MAX_REQUESTS
                value: "2"
              - name: SERVICE_DISCOVERER_URL
                value: http://service-discoverer.default.svc.cluster.local
            command: 
            - /app/main
          restartPolicy: Never